"""geo block coordinates

Revision ID: 753f7edff676
Revises: c0813682b11f
Create Date: 2026-08-13 03:55:02.427669

"""
from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision = '753f7edff676'
down_revision = 'c0813682b11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_blocks', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('geo_blocks', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('geo_blocks', 'longitude')
    op.drop_column('geo_blocks', 'latitude')
    # ### end Alembic commands ###
