"""signal plane and topic taxonomy

Revision ID: c0813682b11f
Revises: f78fa1556152
Create Date: 2026-08-12 07:12:37.976217

"""
from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision = 'c0813682b11f'
down_revision = 'f78fa1556152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_blocks',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('block_name', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_blocks_district'), 'geo_blocks', ['district'], unique=False)
    op.create_table('alerts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('topic_category', sa.String(length=50), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=True),
    sa.Column('geo_block_id', app.db.types.GUID(), nullable=False),
    sa.Column('period_bucket', sa.String(length=10), nullable=False),
    sa.Column('observed_count', sa.Integer(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('baseline_stddev', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_simulated', sa.Integer(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', app.db.types.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['geo_block_id'], ['geo_blocks.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_events',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('topic_category', sa.String(length=50), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=True),
    sa.Column('geo_block_id', app.db.types.GUID(), nullable=False),
    sa.Column('day_bucket', sa.String(length=10), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('is_simulated', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['geo_block_id'], ['geo_blocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_events_day_bucket'), 'signal_events', ['day_bucket'], unique=False)
    op.create_index(op.f('ix_signal_events_geo_block_id'), 'signal_events', ['geo_block_id'], unique=False)
    op.create_index(op.f('ix_signal_events_topic_category'), 'signal_events', ['topic_category'], unique=False)
    op.add_column('health_queries', sa.Column('intent', sa.String(length=50), nullable=True))
    op.add_column('health_queries', sa.Column('topic_category', sa.String(length=50), nullable=True))
    op.add_column('health_queries', sa.Column('topic_tag', sa.String(length=100), nullable=True))
    op.add_column('knowledge_documents', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('knowledge_documents', sa.Column('authority_score', sa.Float(), nullable=True))
    op.add_column('knowledge_documents', sa.Column('published_date', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_knowledge_documents_category'), 'knowledge_documents', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_documents_category'), table_name='knowledge_documents')
    op.drop_column('knowledge_documents', 'published_date')
    op.drop_column('knowledge_documents', 'authority_score')
    op.drop_column('knowledge_documents', 'category')
    op.drop_column('health_queries', 'topic_tag')
    op.drop_column('health_queries', 'topic_category')
    op.drop_column('health_queries', 'intent')
    op.drop_index(op.f('ix_signal_events_topic_category'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_geo_block_id'), table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_day_bucket'), table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_geo_blocks_district'), table_name='geo_blocks')
    op.drop_table('geo_blocks')
    # ### end Alembic commands ###
