"""initial schema

Revision ID: f78fa1556152
Revises: 
Create Date: 2026-08-11 03:21:41.836579

"""
from alembic import op
import sqlalchemy as sa
import app.db.types


# revision identifiers, used by Alembic.
revision = 'f78fa1556152'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymized_symptom_reports',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('symptom_tag', sa.String(length=100), nullable=False),
    sa.Column('district_bucket', sa.String(length=100), nullable=False),
    sa.Column('age_bucket', sa.String(length=20), nullable=True),
    sa.Column('week_bucket', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anonymized_symptom_reports_district_bucket'), 'anonymized_symptom_reports', ['district_bucket'], unique=False)
    op.create_index(op.f('ix_anonymized_symptom_reports_symptom_tag'), 'anonymized_symptom_reports', ['symptom_tag'], unique=False)
    op.create_index(op.f('ix_anonymized_symptom_reports_week_bucket'), 'anonymized_symptom_reports', ['week_bucket'], unique=False)
    op.create_table('health_facilities',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_facilities_district'), 'health_facilities', ['district'], unique=False)
    op.create_table('health_schemes',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=False),
    sa.Column('how_to_apply', sa.Text(), nullable=False),
    sa.Column('official_url', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_documents',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('topic_tag', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('embedding_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_topic_tag'), 'knowledge_documents', ['topic_tag'], unique=False)
    op.create_table('myth_facts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('myth', sa.Text(), nullable=False),
    sa.Column('fact', sa.Text(), nullable=False),
    sa.Column('topic_tag', sa.String(length=100), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_myth_facts_topic_tag'), 'myth_facts', ['topic_tag'], unique=False)
    op.create_table('users',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('citizen', 'health_official', 'admin', name='userrole'), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('consent_records',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('early_awareness_signals',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('symptom_tag', sa.String(length=100), nullable=False),
    sa.Column('district_bucket', sa.String(length=100), nullable=False),
    sa.Column('week_bucket', sa.String(length=10), nullable=False),
    sa.Column('observed_count', sa.Integer(), nullable=False),
    sa.Column('baseline_mean', sa.Float(), nullable=False),
    sa.Column('baseline_stddev', sa.Float(), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', app.db.types.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_queries',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', 'or_', name='querylanguage'), nullable=True),
    sa.Column('ai_response_text', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('safety_flag', sa.String(length=50), nullable=True),
    sa.Column('ai_provider', sa.String(length=20), nullable=True),
    sa.Column('detected_symptom_tags', sa.Text(), nullable=True),
    sa.Column('contributed_to_public_health', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_queries_session_id'), 'health_queries', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_queries_session_id'), table_name='health_queries')
    op.drop_table('health_queries')
    op.drop_table('early_awareness_signals')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_myth_facts_topic_tag'), table_name='myth_facts')
    op.drop_table('myth_facts')
    op.drop_index(op.f('ix_knowledge_documents_topic_tag'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_table('health_schemes')
    op.drop_index(op.f('ix_health_facilities_district'), table_name='health_facilities')
    op.drop_table('health_facilities')
    op.drop_index(op.f('ix_anonymized_symptom_reports_week_bucket'), table_name='anonymized_symptom_reports')
    op.drop_index(op.f('ix_anonymized_symptom_reports_symptom_tag'), table_name='anonymized_symptom_reports')
    op.drop_index(op.f('ix_anonymized_symptom_reports_district_bucket'), table_name='anonymized_symptom_reports')
    op.drop_table('anonymized_symptom_reports')
    # ### end Alembic commands ###
